name: Windows build and tests

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v7.0.1
        with:
          persist-credentials: false
      - name: Compile
        shell: pwsh
        run: ./scripts/Build.ps1
      - name: Test protocol
        shell: pwsh
        run: ./scripts/Test.ps1
